#!/bin/sh
#
# Shell script to start SNAP application -- place this file in /etc/init.d/ 
#

start() {
	echo -n "Starting TCP Raw Client: "
	/usr/bin/python /root/tcpraw/remote_daemon.py start
	echo "done"
}
stop() {
	echo -n "Stopping TCP Raw Client: "
	/usr/bin/python /root/tcpraw/remote_daemon.py stop
	echo "done"
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

